# Neural Networks!
In this example, we are going to make a basic neural network that trains the MNIST fashion dataset.

## Setup
There are two new imports here - Tensorflow and Keras.

Tensorflow - 

Keras - a high-level neural networks API for Python

In [1]:
import tensorflow as tf
from tensorflow import keras as kr
import numpy as np
import matplotlib.pyplot as plt

## Loading the dataset
Instead of using Pandas to load a dataset and read a CSV file, Keras has a feature allowing the programmer to automatically download and use datasets. In this example, we are going to use Keras' fashion dataset (from MNIST).

In [9]:
mnist = kr.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

## This... does something

In [16]:
print(train_images)
print(test_images)

print(type(train_images))
print(type(test_images))

train_images = train_images / 255
test_images  = test_images  / 255

# print(train_images)
# print(test_images)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
[[[0. 0. 0

## The model
Now it is time to create the neural network. We will use Keras' Sequentual network.

In [10]:
model = kr.Sequential([
    kr.layers.Flatten(
        input_shape = (28, 28)
    ),
    kr.layers.Dense(128, activation=tf.nn.relu),
    kr.layers.Dense(10, activation=tf.nn.softmax)
])

In [11]:
model.compile(
    optimizer = 'adam',
    loss      = 'sparse_categorical_crossentropy',
    metrics   = ['accuracy']
)

## Training the model
Now that the model has been created, we can train the neural network with our training data and training labels.

In [12]:
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
60000/60000 [==============================] - 2s 32us/sample - loss: 3.1128 - acc: 0.7035
Epoch 2/5
60000/60000 [==============================] - 2s 31us/sample - loss: 0.6761 - acc: 0.7786
Epoch 3/5
60000/60000 [==============================] - 2s 31us/sample - loss: 0.5741 - acc: 0.8056
Epoch 4/5
60000/60000 [==============================] - 2s 31us/sample - loss: 0.5456 - acc: 0.8179
Epoch 5/5
60000/60000 [==============================] - 2s 31us/sample - loss: 0.5272 - acc: 0.8245


## Analysis
We can analyze the accuracy of our model.

In [21]:
print("Accuracy: " + str(model.metrics[0]))

Accuracy: <tensorflow.python.keras.metrics.MeanMetricWrapper object at 0xb50bc00f0>


In [25]:
predictions = model.predict(test_images)
print(predictions)

[[0.02219748 0.01056086 0.1391381  ... 0.01571777 0.02643525 0.00679331]
 [0.02219688 0.01056072 0.13913344 ... 0.0157161  0.02643532 0.00679287]
 [0.02219743 0.01056097 0.13913713 ... 0.01571676 0.02643504 0.00679299]
 ...
 [0.02219741 0.01056083 0.13913777 ... 0.01571727 0.02643517 0.00679306]
 [0.0221974  0.01056098 0.13913731 ... 0.01571711 0.02643493 0.00679309]
 [0.02219744 0.01056076 0.13913895 ... 0.01571791 0.02643517 0.00679327]]
